[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-1420
monitor_port = /dev/cu.usbserial-1420
lib_deps =
    fastled/FastLED@^3.7.0
    pololu/PololuMaestro@^1.0.0
    https://github.com/DFRobot/DFRobot_DF1201S.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
