[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.Maker-736F
monitor_port = /dev/cu.Maker-736F
lib_deps =
    fastled/FastLED@^3.7.0
    pololu/PololuMaestro@^1.0.0
    dfrobot/DFRobotDFPlayerMini@^1.0.6
